spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: projectman
    password: mustard2
